### ISSUE TITLE
Scheduler Action

### ISSUE THREAD

**Issue by motorina0** [bitkarrot/scheduler#8]
- each time a cron job is triggered it should invoke one action
- the action is a REST HTTP call
  - please see below some screens from [Postman](https://www.postman.com/)
  - we can have something similar
  - the example below calls an API that updates a certain extension to the latest version
    - the API does not exist yet, is for demo purposes only
- we should not add support for OS wise actions (like `rmdir`) for now (keep it simple(r))
- the result of the job execution should be saved in a table (HTTP success status and response body if any)
    - this way the user can check that the action was executed at the correct time with the correct params

**Call Config:**
![image](https://github.com/bitkarrot/scheduler/assets/2951406/86f151a0-b20f-4e13-8f4f-b68d408f6089)

**Call Body**
![image](https://github.com/bitkarrot/scheduler/assets/2951406/3de7b726-dc9d-4458-9b3e-fe5896ef72c2)

**Comment by motorina0** [comment]
In the backend a call of this form will be made each time a job is executed:

```py
async with httpx.AsyncClient() as client:
    resp = await client.get(    # action can be any HTTP verb (GET, PUT, POST, etc) set in the job config
        url,                    # from the job config
        headers,                # from the job config
    )
    save_job_execution(resp.status_code, resp.text())
```

**Comment by bitkarrot** [comment]
@motorina0  OK. I think the directions are clear.

The python-crontabs module would store the X-API-Key values as environment variables in the crontab file, so each individual job will have its own set of env vars. 

Assuming there is no need for global env vars, I'll remove the Global Environment variables box that is currently at the bottom of the extension right now. 

Please do let me know if incorrect! thanks.

**Comment by motorina0** [comment]
Regarding running jobs:
 - there should be only one command file
 - the `job_id` is passed to the command file
 - the command file fetches the full job details from the DB and executes the HTTP call

Adapting a simple example from [here](https://stackabuse.com/scheduling-jobs-with-python-crontab/):
```py
from crontab import CronTab

cron = CronTab(user='username')
job = cron.new(command='python lnbits/utils/cron-job.py') # pass the job_id param somehow
job.minute.every(1)

cron.write()
```

 - `cron-job.py`:
```py
# imports go here

# extract job_id param
# query DB for job

async with httpx.AsyncClient() as client:
    resp = await client.get(    # action can be any HTTP verb (GET, PUT, POST, etc) set in the job config
        url,                    # from the job config
        headers,                # from the job config
    )
    save_job_execution(resp.status_code, resp.text())

```

**Note**: 
 - I'm not sure if the job creation example is the latest and greatest way of starting jobs with the `crontab` extension. 
 - its just to illustrate the flow

**Comment by bitkarrot** [comment]
Working on testing the extension install now. 

Any suggestions on where to put the dependency, would be helpful. 
Right now the python-crontab dependency is in the requirements.txt file but the user has to install it themselves, its not on the LNBits main poetry toml. 

Also the user must set the username that has access to system /usr/bin/crontab
and they need to specify their LNBITS Install, as the crontab script needs to call the API and does not inherit the LNBits environment. I've put these two variables in a .env file, but there is no UI to edit this directly right now. 

Implemented as you suggested using a run_cron_job.py script. 

<img width="605" alt="Screenshot 2023-10-09 at 1 33 41 PM" src="https://github.com/bitkarrot/scheduler/assets/73979971/b6d67d66-b8bf-4bb8-8850-436aa545493e">

<img width="908" alt="Screenshot 2023-10-09 at 1 33 27 PM" src="https://github.com/bitkarrot/scheduler/assets/73979971/cbf6b0a8-2f3a-4734-8527-cdeb51147eb2">

**Comment by motorina0** [comment]
> Any suggestions on where to put the dependency, would be helpful.
- please open a PR on the `lnbits/lnbits` repo with the new dependency
- this PR should be merged before releasing the extension


> as the crontab script needs to call the API and does not inherit the LNBits environment
- relative paths should be supported in the front-end
- if a relative path is used then the back-end must add `http://${HOST}/${PORT}` 

> Also the user must set the username that has access to system /usr/bin/crontab
- why is a OS user required? what happens on non-linux system?

**Comment by bitkarrot** [comment]
According to the docs, there are three ways to do it, with Linux. 
One of the ways requires the username. 

Do we want to enable the username? I know for OSX, I needed it. 

<img width="750" alt="Screenshot 2023-10-11 at 3 24 41 PM" src="https://github.com/bitkarrot/scheduler/assets/73979971/cb62d3ec-93e8-4607-81f4-a52fadfa7330">

**Comment by motorina0** [comment]
> Do we want to enable the username? 

- we want to keep this as simple as possible for the users that install the extension
- it looks like the `username` option is not mandatory, that is good

> I know for OSX, I needed it.
- you mean you had to take extra steps in order to use the lib?
- we should limit/automate that as much as possible

**Comment by bitkarrot** [comment]
OK I am testing this with both Ubuntu and OSX. Will try to have everything working with latest 0.11 this weekend. (this week has been a bit busy)

**Comment by bitkarrot** [comment]
> 
>     * if a relative path is used then the back-end must add `http://${HOST}/${PORT}`
> 

Regarding - I have this script running when the cron job is triggered but is does not have the LNBits environment, I put it in as an env variable in .env but if you have a better way of accessing it, please suggest!

https://github.com/bitkarrot/scheduler/blob/2ceb03e4e14002d55c8ecd890afa3d3d654bde63/run_cron_job.py#L20

extension updated to allow for LNBits v0.11 but still need to do more testing.

**Comment by motorina0** [comment]
> Regarding - I have this script running when the cron job is triggered but is does not have the LNBits environment, I put it in as an env variable in .env but if you have a better way of accessing it, please suggest!

- `.env` file has these properties:
```properties
HOST=127.0.0.1
PORT=5000
```

- data can also be passes to the job in the `comment` field (or something similar), right?

**Comment by bitkarrot** [comment]
> ```ini
> HOST=127.0.0.1
> PORT=5000
> ```
> 
>     * data can also be passes to the job in the `comment` field (or something similar), right?

yes I know that the HOST/PORT is in the LNBits .env, but that cron script unfortunately runs outside of the LNBits environment as its called by system crontab which doesn't inherit the LNBits environment. 

I can pass the HOST/PORT in, just like the job ID and adminKey is passed in right now (this is testnet example). 

Perhaps this is better way to do it.

Ok I will test and get back to you. Thanks @motorina0 

<img width="925" alt="Screenshot 2023-10-26 at 11 17 53 AM" src="https://github.com/bitkarrot/scheduler/assets/73979971/ed992a9a-7139-4c96-8fda-8e93797fcbcb">

**Comment by bitkarrot** [comment]
OK I fixed the above, made a release. It should be working with basic functionality now, validation can improve but please have a look. https://github.com/bitkarrot/scheduler/releases/tag/v0.0.9, @motorina0

**Comment by bitkarrot** [comment]
tested with sqlitedb only so far, no postgres
